name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 11 PM UTC, which is 12 AM in Morocco
    - cron: '0 23 * * *'


jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: athul/waka-readme@v0.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
